// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // <--- CHANGED: Import standard Google Fonts
import "./globals.css";

const inter = Inter({ // <--- CHANGED: Use Inter for sans-serif
  subsets: ["latin"],
  variable: "--font-inter-sans", // You might want to update your CSS variables if you use these
});

const robotoMono = Roboto_Mono({ // <--- CHANGED: Use Roboto Mono for monospace
  subsets: ["latin"],
  variable: "--font-roboto-mono", // You might want to update your CSS variables if you use these
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`} // <--- CHANGED: Apply new font variables
      >
        {children}
      </body>
    </html>
  );
}